---
# tasks file for docker_role
- name: debug os distro
  debug:
    var: ansible_facts['distribution']
  tags: docker
  
- name: Add docker repository Fedora
  shell: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
  when: ansible_facts['distribution'] == "Fedora"

- name: Install yum-utils package CentOS
  package:
    name: yum-utils
    state: latest
  when: ansible_facts['distribution'] == "CentOS"

- name: Add docker repository CentOS
  shell: dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  when: ansible_facts['distribution'] == "CentOS"

- name: Install docker packages
  dnf:
    name: "{{ docker_packages }}"
    state: latest
  tags: docker
  register: install

- name: Update docker compose module
  shell: ansible-galaxy collection install community.docker
  tags: docker
  when: install.changed
  
- name: Enable docker service
  service:
    name: docker 
    state: started
    enabled: yes
  tags: docker