---
- name: Install SSH packages
  ansible.builtin.dnf:
    name: openssh-server
    state: present

- name: Configure SSHD - Port
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^#?Port'
    line: "Port {{ role_ssh_sshport | default('2229') }}"
    state: present
  notify: Restart sshd service

- name: Configure SSHD - PubkeyAuthentication
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^#?PubkeyAuthentication'
    line: "PubkeyAuthentication yes"
    state: present
  notify: Restart sshd service

- name: Configure SSHD - PasswordAuthentication
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication'
    line: "PasswordAuthentication no"
    state: present
  notify: Restart sshd service

- name: Configure SSHD - PermitRootLogin
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^#?PermitRootLogin'
    line: "PermitRootLogin no"
    state: present
  notify: Restart sshd service

- name: Add custom sshd port to SELinux
  community.general.seport:
    ports: "{{ role_ssh_sshport | default('2229') }}"
    proto: tcp
    setype: ssh_port_t
    state: present
  when: ansible_facts.selinux.status is defined and ansible_facts.selinux.status == "enabled"

- name: Allow SSH in firewalld
  ansible.posix.firewalld:
    port: "{{ role_ssh_sshport | default('2229') }}/tcp"
    permanent: true
    state: enabled
    immediate: true
  when: ansible_facts.packages['firewalld'] is defined
