---
- name: Install SSH packages
  ansible.builtin.dnf:
    name: openssh-server
    state: present

- name: Configure SSHD
  ansible.posix.sshd:
    port: "{{ role_ssh_sshport | default('2229') }}"
    pubkeyauthentication: yes
    passwordauthentication: no
    challengeuserresponseauthentication: no
    permitrootlogin: no
    firewalld: yes
  notify: Restart sshd service

- name: Add custom sshd port to SELinux
  community.general.seport:
    ports: "{{ role_ssh_sshport | default('2229') }}"
    proto: tcp
    setype: ssh_port_t
    state: present
  when: ansible_facts.selinux.status is defined and ansible_facts.selinux.status == "enabled"

- name: Allow SSH in firewalld
  ansible.posix.firewalld:
    port: "{{ role_ssh_sshport | default('2229') }}/tcp"
    permanent: yes
    state: enabled
    immediate: yes
