services:
#Service that allows resolving containers hostname form docker host
  dnsproxy:
    container_name: dns.mageddo
    image: defreitas/dns-proxy-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/resolv.conf:/etc/resolv.conf
    networks:
      - lab_net
  ubuntu1:
    container_name: ubuntu1
    hostname: ubuntu1
    image: 'ubuntu_ssh:latest'
    restart: unless-stopped
    networks:
      - lab_net
  ubuntu2:
    container_name: ubuntu2
    hostname: ubuntu2
    image: 'ubuntu_ssh:latest'
    restart: unless-stopped
    networks:
    - lab_net
networks:
    lab_net:
      name: lab_net