---
wireguard_private_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  65643536313934326466333539363030623463343937313834363266623635666333626237626434
  3232306661613630353232313234343964623936663062320a313832616335666661363166663362
  61633934383132613130366139613834383063636433363033376163303735336433303161316230
  3436383539636232320a346262646362656161313738373031343365353834646265626361386438
  66393565636162303163353366663163323534626562643130326439326634323166346234613835
  6263313436303930653634383465613963633862316436363732
wireguard_public_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  31313163363738353635323838393938666235633431346566343433383732383663303538313435
  3561626632306362353534333666663864393030393563380a343965353161386235376636613737
  39623765626431633565353734356263663233653836336530383536323039633932323261643931
  3731386139313966320a376538626161646436393332336237393735666535343436353563363834
  38643665393763616631616566626162373230326534663731313164653965303437653838326462
  3539356262303539653630616539303534636464646339633635
wireguard_preshared_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  32386134613334303137363366653836616634626135663866663134396661626662333962616530
  6236653865356130376261643563366366366634323438650a663565346239343161653865376533
  63323338316361363332376639313366356435346332343464383333613135353561393530313638
  3236343031326435300a313466336662303434313363373063336233663561393461366566366433
  66373765646335333666633531613761313661326165346237323161363331383630356130396638
  6133616233643464663565313733643935343564313133363433
wireguard_endpoint: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  35313236343934376131376530346134656238333038386430346630313964366233613266626564
  3665383733616539666636356362663539323265646561370a376461613234613737666563643465
  30363935376631393637623766376437363333623838643232393338313439653539326632623166
  3361323632633532310a666463653766303838313138343731616231653332393837363638313230
  34373433313330303335353166343136633338633737613034323034373035383432
