containers:
  hosts:
    ubuntu-test:
      ansible_host: 172.18.0.10
      ansible_user: ansible_user
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    rhellike-test:
      ansible_host: 172.18.0.11
      ansible_user: ansible_user
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

vms:
  hosts:
    ansible-debian:
      ansible_host: 192.168.122.10
      ansible_user: root
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ansible-almalinux:
      ansible_host: 192.168.122.11
      ansible_user: root
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  children:
    debian_hosts:
      hosts:
        ansible-debian:
    rhel_hosts:
      hosts:
        ansible-almalinux:
