vault_user_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          39643236356339643736643539663332366639336536613437646363303064383330633465346561
          3639356666656566346639623362313463336438613061310a303830663033396364346461653736
          61343733366430356334663165653261306164616663336530383434666232646639366166323166
          6333383931616565620a626132376531623065663131303665396633363236613338643961356133
          3038
