---
# Encrypted vault containing sensitive variables for all hosts
# Use --vault-password-file to decrypt when running playbooks
vault_user_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  66366131306532383032326136623530636663326639376162326464373131303264613762346365
  3763346134373066643734326562323365323534623138630a323737346532323538343030646234
  37616631623963386666613632336262376165643730353231326539393435333537626234633534
  3030393163323837390a333564363133353564393531643231653264366335323630383733626136
  6233
