---
- name: Create groups
  ansible.builtin.group:
    name: "{{ item.groups }}"
    state: present
  when: item.groups is defined
  loop: "{{ role_users_user_details }}"

- name: Create users - with password
  ansible.builtin.user:
    name: "{{ item.username }}"
    groups: "{{ item.groups | default('') }}"
    append: true
    create_home: true
    password: "{{ vault_user_password | password_hash('sha512') }}"
    password_expire_max: -1
    comment: "Created during provisioning"
  loop: "{{ role_users_user_details }}"
  when: vault_user_password is defined

- name: Create users - without password (locked)
  ansible.builtin.user:
    name: "{{ item.username }}"
    groups: "{{ item.groups | default('') }}"
    append: true
    create_home: true
    password: "*"
    password_expire_max: -1
    comment: "Created during provisioning"
  loop: "{{ role_users_user_details }}"
  when: vault_user_password is undefined

- name: Add user to sudoers
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    insertafter: EOF
    line: '{{ item.username }} ALL=(ALL) NOPASSWD: ALL'
    regexp: '^{{ item.username }} .*'
    state: present
  when: item.sudoers is true
  loop: '{{ role_users_user_details }}'

- name: Create .ssh directory
  ansible.builtin.file:
    path: /home/{{ item.username }}/.ssh
    state: directory
    mode: '0750'
    modification_time: preserve
    access_time: preserve
  loop: '{{ role_users_user_details }}'

- name: Generate SSH key on remote host
  remote_user: "{{ item.username }}"
  become: yes
  become_user: "{{ item.username }}"
  community.crypto.openssh_keypair:
    path: "/home/{{ item.username }}/.ssh/id_rsa"
    owner: "{{ item.username }}"
    group: "{{ item.username }}"
    mode: '0600'
  loop: "{{ role_users_user_details }}"

- name: Backup private keys to controller
  ansible.builtin.fetch:
    src: "/home/{{ item.username }}/.ssh/id_rsa"
    dest: "{{ playbook_dir }}/ssh_keys/{{ inventory_hostname }}/{{ item.username }}"
    flat: yes
    mode: '0600'
  loop: "{{ role_users_user_details }}"

- name: Backup public keys to controller
  ansible.builtin.fetch:
    src: "/home/{{ item.username }}/.ssh/id_rsa.pub"
    dest: "{{ playbook_dir }}/ssh_keys/{{ inventory_hostname }}/{{ item.username }}.pub"
    flat: yes
  loop: "{{ role_users_user_details }}"

- name: Authorize admin pub_key in authorized_keys
  ansible.posix.authorized_key:
    user: "{{ item.username }}"
    state: present
    key: "{{ lookup('file', 'files/main.pub') }}"
  loop: "{{ role_users_user_details }}"
